@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Context.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Container.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Component.puml

title Component Diagram

Container_Boundary(optimusPrime, "Optimus Prime") {
    Component(proxyServiceDomain, "proxy-service/domain", "scala DSL")
    Component(proxyServiceHttpServer, "proxy-service/http-server", "http4s + tapir", "exposes REST endpoints")
    Component(proxyServiceGRPCClient, "proxy-service/grpc-server", "zio grpc + protobuf")
    Component(primeNumberServerDomain, "prime-number-server/domain", "scala DSL")
    Component(primeNumberGRPCServer, "prime-number-server/grpc-server", "zio grpc + protobuf")
}

Rel(proxyServiceHttpServer, proxyServiceDomain, "Uses")
Rel(primeNumberGRPCServer, primeNumberServerDomain, "Uses")
Rel(httpClient, domain, "Implements")
Rel(formatter, domain, "Implements")
Rel(spreadsheet, domain, "Implements")
Rel(fileStorage, domain, "Implements")

Rel(app, httpServer, "Wires")
Rel(app, httpClient, "Wires")
Rel(app, formatter, "Wires")
Rel(app, fileStorage, "Wires")
Rel(app, spreadsheet, "Wires")


@enduml