@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Context.puml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v1.0.0/C4_Container.puml

title Container Diagram

Person(User, "User")

Boundary(Optimus, "Optimus") {
    System(ProxyService, "proxy-service")
    System(PrimeNumberServer, "proxy-number-server")
}

Rel(User, ProxyService, "Asks for a sequence of prime numbers up to the given number", "http")
Rel(ProxyService, PrimeNumberServer, "Asks for a sequence of prime numbers up to the given number", "grpc")
@enduml